# Generated by Django 3.0.7 on 2020-06-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_internal_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='internal_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
